version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html:z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:z
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    
  web:
    build:
      context: src/E_Global_Zone-Web
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - laravel

  mysql:
    image: mysql:5.7.26
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:z
    environment:
      MYSQL_DATABASE: e_global_zone
      MYSQL_USER: oic_yju
      MYSQL_PASSWORD: oic_yju
      MYSQL_ROOT_PASSWORD: oic_yju
      # SERVICE_TAGS: dev
      SERVICE_TAGS: service
      SERVICE_NAME: mysql
      TZ: "Asia/Seoul"
    networks:
      - laravel

  php:
    build:
      context: src/E_Global_Zone
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:z
    environment:
      TZ: "Asia/Seoul"
      MYSQL_DATABASE: e_global_zone
      MYSQL_USER: "oic_yju"
      MYSQL_PASSWORD: "oic_yju"
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel
